# Generated by Django 3.2.7 on 2021-12-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_initial'),
        ('deals', '0001_initial'),
        ('settings', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitsplit',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.entity'),
        ),
        migrations.AddField(
            model_name='profitsplit',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.sale'),
        ),
        migrations.AddField(
            model_name='primecostitems',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prime_cost_items', to='deals.rooms'),
        ),
        migrations.AddField(
            model_name='mypurchasedetails',
            name='accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_accountant_details', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='mypurchasedetails',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_agent_details', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='mypurchasedetails',
            name='bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_bank_details', to='leads.bank'),
        ),
        migrations.AddField(
            model_name='mypurchasedetails',
            name='conveyancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_conveyancer_details', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='mypurchasedetails',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_entity_details', to='settings.entity'),
        ),
        migrations.AddField(
            model_name='mypurchasedetails',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_purchase_details', to='deals.purchase'),
        ),
        migrations.AddField(
            model_name='materials',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='deals.rooms'),
        ),
        migrations.AddField(
            model_name='listforsale',
            name='deal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_for_sale', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='listforsale',
            name='real_estate_company_agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_agent', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='internaltasksformyself',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_for_myself', to='deals.rooms'),
        ),
        migrations.AddField(
            model_name='images',
            name='renovation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='deals.renovation'),
        ),
        migrations.AddField(
            model_name='holdingcosts',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.purchase'),
        ),
        migrations.AddField(
            model_name='feasibilityreport',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.purchase'),
        ),
        migrations.AddField(
            model_name='externaltasksformyself',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_tasks_for_myself', to='deals.external'),
        ),
        migrations.AddField(
            model_name='externaltasks',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_tasks', to='deals.external'),
        ),
        migrations.AddField(
            model_name='externaltasks',
            name='service_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_tasks', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='externalmaterials',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_materials', to='deals.external'),
        ),
        migrations.AddField(
            model_name='external',
            name='renovation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external', to='deals.renovation'),
        ),
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AddField(
            model_name='afcacomplaintlodged',
            name='deal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afca_complaint_lodged', to='deals.deal'),
        ),
    ]
