# Generated by Django 3.2.7 on 2021-12-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitor',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
