# Generated by Django 3.2.7 on 2021-12-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('deals', '0004_auto_20211215_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.propertyowner'),
        ),
    ]
