# Generated by Django 3.2.7 on 2021-12-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_purchase_renovation_required'),
        ('deals', '0005_solicitor_owner'),
    ]

    operations = [
    ]
