# Generated by Django 3.2.7 on 2022-01-03 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_auto_20211227_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitor',
            name='owner',
        ),
        migrations.AddField(
            model_name='solicitor',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.deal'),
        ),
    ]
