# Generated by Django 3.2.7 on 2022-01-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_auto_20220103_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitor',
            name='deal',
        ),
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banknew',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='executor',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='liquidator',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitor',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
