# Generated by Django 3.2.7 on 2022-01-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_alter_solicitor_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listforsale',
            name='real_estate_company_agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_agent', to='deals.agent'),
        ),
    ]
