# Generated by Django 3.2.7 on 2022-01-06 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
        ('deals', '0015_alter_listforsale_real_estate_company_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='listforsale',
            name='agent',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='deals.agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listforsale',
            name='real_estate_company_agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_agent', to='contacts.contact'),
        ),
    ]
