# Generated by Django 3.2.7 on 2022-01-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
        ('deals', '0017_solicitor_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listforsale',
            name='real_estate_company_agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_agent', to='contacts.contact'),
        ),
    ]
