# Generated by Django 3.2.7 on 2022-01-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_alter_listforsale_real_estate_company_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='select',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banknew',
            name='select',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='executor',
            name='select',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='family',
            name='select',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liquidator',
            name='select',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='other',
            name='select',
            field=models.BooleanField(default=True),
        ),
    ]
