# Generated by Django 3.2.7 on 2022-01-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0019_auto_20220110_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypurchasedetails',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_agent_details', to='deals.agent'),
        ),
    ]
