# Generated by Django 3.2.7 on 2022-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0020_alter_mypurchasedetails_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitor',
            name='deal',
            field=models.IntegerField(default=0),
        ),
    ]
