# Generated by Django 3.2.7 on 2022-01-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0021_alter_solicitor_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitor',
            old_name='deal',
            new_name='deal_id',
        ),
    ]
