# Generated by Django 3.2.7 on 2022-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0022_rename_deal_solicitor_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='deal_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banknew',
            name='deal_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executor',
            name='deal_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='family',
            name='deal_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidator',
            name='deal_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='other',
            name='deal_id',
            field=models.IntegerField(default=0),
        ),
    ]
