# Generated by Django 3.2.7 on 2021-12-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_bank_mortgaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='mortgaged',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, verbose_name='Mortgaged'),
        ),
    ]
